
server:
  port: 8080

spring:
  application:
    name: reto-tecnico-max-leon
  cloud:
    config:
      profile: dev


  #para swagger:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher