spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/maxsoft21/service-configuration-reto-between
          clone-on-start: true
server:
  port: 8888
